server:
  port: 9003

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      zipkin:
        base-url: http://localhost:9411
        boot:
          admin:
            client:
              url: http://localhost:9004
      redis:
        database: 2
        host: 127.0.0.1
        jedis:
          pool:
            max-active: 20
      rabbitmq:
        host: ${RABBIT_MQ_HOST:localhost}
        port:  ${RABBIT_MQ_PORT:5672}
        username:
        password:
      feign:
        httpclient:
          enabled: false
        okhttp:
          enabled: true
        compression:
          request:
            enabled: true
            mime-types: text/xml,application/xml,application/json
            min-request-size: 2048
          response:
            enabled: true
      hystrix:
        threadpool:
          default:
            coreSize: 1000 ##并发执行的最大线程数，默认10
            maxQueueSize: 1000 ##BlockingQueue的最大队列数
            queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
        command:
          default:
            execution:
              isolation:
                thread:
                  timeoutInMilliseconds: 10000
      sentinel:
        transport:
          dashboard: localhost:8080
      sleuth:
        enabled: true
        http:
          legacy:
            enabled: true
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: url-proxy-1
          uri: https://blog.csdn.net
          predicates:
          - Path=/meteor_93
        - id: anser-admin
          uri: http://127.0.0.1:9001/admin  #lb://admin
          order: 8000
          predicates:
          - Path=/api/admin/**
          filters:
          - StripPrefix=1
        - id: anser-auth
          uri: http://127.0.0.1:9002/auth  #  lb://auth
          order: 8001
          predicates:
          - Path=/api/auth/**
          filters:
          - StripPrefix=1
#      - id: gateway-service
#        uri: https://www.baidu.com
#        order: 0
#        predicates:
#        - After=2020-04-04T00:00:00+08:00[Asia/Shanghai]

#logging:
#  level:
#    com.jimy.anser.security.gate.v2: info

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false