server:
  servlet:
    context-path: /admin
  port: 9001

spring:
  application:
    name: anser-admin
  zipkin:
    base-url: http://localhost:9411
    boot:
      admin:
        client:
          url: http://localhost:9004
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo1?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  hystrix:
    # 开启Feign的Hystrix熔断器支持
    enabled: true