server:
  servlet:
    context-path: /admin
  port: 9001

spring:
  application:
    name: anser-admin
  zipkin:
    base-url: http://localhost:9411
    boot:
      admin:
        client:
          url: http://localhost:9004
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  hystrix:
    # 开启Feign的Hystrix熔断器支持
    enabled: true